### ISSUE TITLE
Removing a capture binding and re-adding it removes attributes

### ISSUE THREAD

**Issue by dyaffe** [estuary/ui#588] opened 2023-04-26 23:59 UTC
**Bug**
Steps to recreate:
1. Create a capture from a db
2. Get a bunch of bindings
3. Remove one
4. Re-add it and note that your schema and table name are no longer there

**Expected**
The schema and table name should be there

**Comment by kiahna-tucker** [comment] 2023-04-27 13:45
This is a duplicate of [issue 536](https://github.com/estuary/ui/issues/536) and will be closed.

**Closed by kiahna-tucker** 2023-04-27 13:45 UTC
Labels: bug, duplicate
