### ISSUE TITLE
Display determinate progress bar during discovery and publication creation

### ISSUE THREAD

**Issue by dyaffe** [estuary/ui#518] opened 2023-03-14 15:07 UTC
**Proposal** 
We should add a loading bar when doing a discover or publish that takes the same amount of time as the backend timeout (I think it's 30s).

This will help users understand the max time that a publish or discover can take.

**Comment by kiahna-tucker** [comment] 2023-03-14 18:41
FYI: This is a duplicate of issue #488.

**Closed** 2023-06-08 19:16 UTC
Labels: enhancement, Edit, Create
